import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";

const mexiko = Roboto({
  display: "swap",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Mening 1-Next.js loyiham",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mexiko.className} antialiased`}>{children}</body>
    </html>
  );
}
